name: AEA Deposit

on:
  schedule:
    - cron: "30 0 * * *"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: false
      tags:
        description: 'Manual trigger'
        
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
        echo "Tags: ${{ github.event.inputs.tags }}"
  job_id:
    name: notebook
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run script
      env:
        JOURNAL: ${{ secrets.JOURNAL }}
      run: |
        python src/aea.py -j ${JOURNAL}
    - name: Commit changes
      env:
        USER_EMAIL: ${{ secrets.USER_EMAIL }}
        USER_NAME: ${{ secrets.USER_NAME }}
        ACCESS_TOKEN: ${{ secrets.TOKEN }}
      run: |
        git config --global user.email ${USER_EMAIL}
        git config --global user.name ${USER_NAME}
        git remote set-url origin https://${USER_NAME}:${ACCESS_TOKEN}@github.com/${USER_NAME}/replication-code-stata.git
        git add .
        git diff-index --quiet HEAD || git commit -m "Added AEA deposit data"
        git pull --rebase origin main
        git push -u origin main
